feat(improvements) latest commit of pugiXML & better REDME
tupoy-ya/MenyooMP pull request #4
Opened 2022-11-29 21:28 UTC by Clone69420

2022-11-29 21:35 UTC, tupoy-ya requested changes

2022-11-29 21:35 UTC, tupoy-ya commented on ScriptHookVDotNet.LICENSE.txt
> -  3. This notice may not be removed or altered from any source distribution.
This file is probably for some enum or other stuff which i'm too lazy to find.

2022-11-29 21:35 UTC, tupoy-ya commented on README.md
> +  cd MenyooMP
`cd MenyooMP/Solution`

2022-11-29 22:07 UTC, Clone69420 commented
Is .stignore even needed? Bec you can just put it in .gitignore ig.

2022-11-30 08:21 UTC, tupoy-ya commented
> Is .stignore even needed? Bec you can just put it in .gitignore ig.

.stingore is for [syncthing](https://syncthing.net) which i used to sync my windows VM with my host system.

It's not really needed anymore because i use msvc on linux now.

2022-11-30 17:01 UTC, Clone69420 commented
Idk if u need these weird eGameVersion stuff but should be fine or tested

2022-11-30 17:41 UTC, tupoy-ya commented
It's not just MP fixed version of Menyoo it also just improves code readability (not enough yet), eGameVersion stuff is needed if you use an older version of the game (speedrun patch, pirated, just don't update).

About the `_Build` we should put menyooStuff in the root of the repo `MenyooMP/menyooStuff`

2022-12-01 08:27 UTC, tupoy-ya commented
`Solution/source/Menyoo.rc` is required if you load Menyoo in FiveM and probably with normal ScriptHookV

2022-12-16 14:12 UTC, tupoy-ya requested changes
Forgot to submit this sorry.

2022-12-16 14:12 UTC, tupoy-ya commented on OpenV LICENSE.txt
> +https://github.com/crosire/scripthookvdotnet/blob/dev_v2/LICENSE.txt
Why is this named OpenV LICENSE?

2022-12-16 14:12 UTC, tupoy-ya commented on Solution/source/Memory/GTAmemory.cpp
> +	case eGameVersion::VER_1_0_2699_16_NOSTEAM: case eGameVersion::VER_1_0_2699_16_STEAM:
It's just `VER_1_0_2699_16` without `_STEAM` or `_NOSTEAM` as far as i know.

Here is the enum i have in TupoyeMenu
```cpp
enum eGameVersion : int
{
	VER_1_0_335_2_STEAM,
	VER_1_0_335_2_NOSTEAM,

	VER_1_0_350_1_STEAM,
	VER_1_0_350_2_NOSTEAM,

	VER_1_0_372_2_STEAM,
	VER_1_0_372_2_NOSTEAM,

	VER_1_0_393_2_STEAM,
	VER_1_0_393_2_NOSTEAM,

	VER_1_0_393_4_STEAM,
	VER_1_0_393_4_NOSTEAM,

	VER_1_0_463_1_STEAM,
	VER_1_0_463_1_NOSTEAM,

	VER_1_0_505_2_STEAM,
	VER_1_0_505_2_NOSTEAM,

	VER_1_0_573_1_STEAM,
	VER_1_0_573_1_NOSTEAM,

	VER_1_0_617_1_STEAM,
	VER_1_0_617_1_NOSTEAM,

	VER_1_0_678_1_STEAM,
	VER_1_0_678_1_NOSTEAM,

	VER_1_0_757_2_STEAM,
	VER_1_0_757_2_NOSTEAM,

	VER_1_0_757_4_STEAM,
	VER_1_0_757_4_NOSTEAM,

	VER_1_0_791_2_STEAM,
	VER_1_0_791_2_NOSTEAM,

	VER_1_0_877_1_STEAM,
	VER_1_0_877_1_NOSTEAM,

	VER_1_0_944_2_STEAM,
	VER_1_0_944_2_NOSTEAM,

	VER_1_0_1011_1_STEAM,
	VER_1_0_1011_1_NOSTEAM,

	VER_1_0_1032_1_STEAM,
	VER_1_0_1032_1_NOSTEAM,

	VER_1_0_1103_2_STEAM,
	VER_1_0_1103_2_NOSTEAM,

	VER_1_0_1180_2_STEAM,
	VER_1_0_1180_2_NOSTEAM,

	VER_1_0_1290_1_STEAM,
	VER_1_0_1290_1_NOSTEAM,

	VER_1_0_1365_1_STEAM,
	VER_1_0_1365_1_NOSTEAM,

	VER_1_0_1493_0_STEAM,
	VER_1_0_1493_0_NOSTEAM,

	VER_1_0_1493_1_STEAM,
	VER_1_0_1493_1_NOSTEAM,

	VER_1_0_1604_0_STEAM,
	VER_1_0_1604_0_NOSTEAM,

	VER_1_0_1604_1_STEAM,
	VER_1_0_1604_1_NOSTEAM,
	
	VER_1_0_1737_0_STEAM,
	VER_1_0_1737_0_NOSTEAM,
	
	VER_1_0_1737_6_STEAM,
	VER_1_0_1737_6_NOSTEAM,
	
	VER_1_0_1868_0_STEAM,
	VER_1_0_1868_0_NOSTEAM,
	
	VER_1_0_1868_1_STEAM,
	VER_1_0_1868_1_NOSTEAM,
	VER_1_0_1868_4_EPIC,

	VER_1_0_2060_0_STEAM,
	VER_1_0_2060_0_NOSTEAM,
	
	VER_1_0_2060_1_STEAM,
	VER_1_0_2060_1_NOSTEAM,

	VER_1_0_2189_0_STEAM,
	VER_1_0_2189_0_NOSTEAM,
	
	VER_1_0_2215_0_STEAM,
	VER_1_0_2215_0_NOSTEAM,
	
	VER_1_0_2245_0_STEAM,
	VER_1_0_2245_0_NOSTEAM,

	VER_1_0_2372_0_STEAM,
	VER_1_0_2372_0_NOSTEAM,
	
	VER_1_0_2545_0_STEAM,
	VER_1_0_2545_0_NOSTEAM,

	VER_1_0_2612_0_STEAM,
	VER_1_0_2612_0_NOSTEAM,
	
	VER_1_0_2628_0_STEAM,
	VER_1_0_2628_0_NOSTEAM,

	VER_1_0_2628_2_STEAM,
	VER_1_0_2628_2_NOSTEAM,

	VER_1_0_2699_0_STEAM,
	VER_1_0_2699_0_NOSTEAM,

	VER_1_0_2699_16,
	
	VER_SIZE,
	VER_UNK = -1
};
```

2023-02-05 15:35 UTC, closed without merging